### PR TITLE
Slightly darken fonts for light theme to improve contrast

### PR DESCRIPTION
**Pull request by fossfreedom**
The current font colour for the light theme does not
provide enough of a contrast to be easily legible.  This
commit reduces the contrast colour by approx 7%
This resolves for #406

ubuntu budgie - new development artful running - oracle vm virtualbox_008

compared to current

ubuntu budgie - new development artful running - oracle vm virtualbox_005

### CODE REVIEW

**Comment by Paviluf** [comment]
I can't test for now but it seem much much better on the screenshot. That said I wonder if it's enough ?
The full dark screenshot seem even better.

**Comment by fossfreedom** [comment]
The black font breaks the aesthetic looks of Arc.  I'm trying to ensure we work within the Arc parameters.  I would suggest this needs testing to confirm its usability.  To my eye it works quite nicely.

**Comment by fossfreedom** [comment]
@NicoHood can we merge the current two PRs?

**Comment by NicoHood** [comment]
@fossfreedom I did not test them yet, I can try if my internet is fast enough next week. From just looking at the changes and screenshots it is a good idea, of course. If you think the changes are all good, merge it. If you explicitly wish me to test it first, I will do.

**Comment by fossfreedom** [comment]
I would prefer to have positive feedback first before making the more obvious changes like these.  Next week would be fine.

BTW - please can we aim for a formal signed release in the middle of Jan?  This will then allow me to push to Debian & Ubuntu - specifically I am aiming for Alpha 2 of Ubuntu Budgie 18.04 Feb 1st.

**Comment by NicoHood** [comment]
@fossfreedom okay, I will test and give feedback soon. Sure I can, just remind me or give me a deadline. Those two PRs should be included of course.

**Comment by fossfreedom** [comment]
COP (close of play) Fri 19th Jan.  Cheers.

**Comment by NicoHood** [comment]
Can you please give me some advice how to use the new sass? You made some changes, right? Gulp is not required anymore? You could add this to:
https://github.com/NicoHood/arc-theme/blob/master/HACKING.md

It would be nice if we can automatically generate the css files within the makefile. We can then decide if we still want to commit them or not.

**Comment by NicoHood** [comment]
I've tested the changes and do not see any problem. I am however normally using arc-darker with global dark theme enabled. This change should be fine.

**Comment by NicoHood** [comment]
I found out that the darker colors are not applied to arc-darker:
screenshot from 2018-01-08 20-13-49
screenshot from 2018-01-08 20-14-37

**Comment by fossfreedom** [comment]
odd - very odd - the colours look ok here - just testing the 2018 branch.

I don't recognise that window - is that a GTK+3 app of some-sort - which DE is that?

On 8 January 2018 at 19:15, Nico <notifications@github.com<mailto:notifications@github.com>> wrote:

I found out that the darker colors are not applied to arc-darker:
[screenshot from 2018-01-08 20-13-49]<https://user-images.githubusercontent.com/6888294/34687933-a9611f60-f4b0-11e7-8d20-af60160b5802.png>
[screenshot from 2018-01-08 20-14-37]<https://user-images.githubusercontent.com/6888294/34687938-aac6807a-f4b0-11e7-9349-df48c7a7eb82.png>

**Comment by NicoHood** [comment]
Its the xfce4 setting menu. I noticed this by accident.

**Comment by fossfreedom** [comment]
@NicoHood I'm not an XFCE user so I can't really say if the following change works in general so please can you test?

It appears that that appearance window is a GTK-2 window - so gtk-2 stuff is in common/gtk-2.0

so the text color/fg color between the arc (gtkrc) arc-darker (gtkrc-darker) and arc-dark (gtkrc-dark) are different deliberately at the moment.

ubuntu budgie - new development artful running - oracle vm virtualbox_030

if you change the fields shown  in the picture to be the same as Arc (gtkrc) then the text colour is the same - if you feel this looks better, push a commit on that file

**Pull request merged**
