### PR TITLE
gnome-shell 3.30: fixed bg color of slider

### LINKED ISSUE #125: [GNOME 3.30] Volume/Brightness sliders are difficult to see
### Details

- Distribution (with version): ArchLinux 
- Desktop environment (with version): gnome-shell 3.30.0+25+g179cd0a3c-1
- Arc version/commit (don't put "latest"): arc-solid-gtk-theme-git 20180715.r16.b05cc9d-1
- GTK+ 3 version: 3.24.1
- Installation method (package or source): https://aur.archlinux.org/packages/arc-solid-gtk-theme-git/

Volume/Brightness sliders are difficult to see (dark background)
screenshot from 2018-09-19 21-08-41

### PR DESCRIPTION
**Pull request by spielkind**
This should fix #125

### CODE REVIEW

**Comment by spielkind** [comment]
"real" diff:
```diff
--- 3.18/sass/_common.scss	2018-09-20 19:16:43.156091772 +0200
+++ 3.30/sass/_common.scss	2018-09-20 19:24:29.682995799 +0200
@@ -138,12 +138,12 @@
 // Slider
 //
 .slider {
-  -slider-height: 4px;
-  -slider-background-color: $button_border;                   //background of the trough
-  -slider-border-color: transparentize(black, 1);             //trough border color
-  -slider-active-background-color: $selected_bg_color;        //active trough fill
-  -slider-active-border-color: transparentize(black, 1);      //active trough border
-  -slider-border-width: 0;
+  -barlevel-height: 4px;
+  -barlevel-background-color: $button_border;                   //background of the trough
+  -barlevel-border-color: transparentize(black, 1);             //trough border color
+  -barlevel-active-background-color: $selected_bg_color;        //active trough fill
+  -barlevel-active-border-color: transparentize(black, 1);      //active trough border
+  -barlevel-border-width: 0;
   -slider-handle-radius: 0px;
   height: 18px;
   border: 0 solid transparent;
@@ -152,8 +152,8 @@
   color: transparent;
 
   .popup-menu-item.selected & {
-    -slider-background-color: transparentize(black, 0.8);
-    -slider-active-background-color: $selected_fg_color;
+    -barlevel-background-color: transparentize(black, 0.8);
+    -barlevel-active-background-color: $selected_fg_color;
   }
 }

```

**Comment by NicoHood** [comment]
Did you use an old git revision where a gitignore was missing? There are lots of generated svg files. Please use the latest git and rebase your changes.

Thanks for looking into it!

**Comment by spielkind** [comment]
Hm, I forked the latest master branch, but I removed the symlink (3.30 -> 3.18), copied the whole content from 3.18 to 3.30 and changed just one file in sass folder  - not sure if this is the correct method. As alternative I could remove the "assets" sub folders and symlink these separately to 3.18?

**Comment by NicoHood** [comment]
Why did you remove the symlink? Just keep it!?

**Comment by spielkind** [comment]
As far as I understood it: when I keep the the symlink and change the code in the 3.18 folder will this break the theme for gnome <=3.28?

**Comment by jnsh** [comment]
The updates to _common.scss looks mostly ok, but I think you missed updating the -slider-handle-radius.

However, there are also other updates to the slider scss, and also for the OSD audio-level bar, due to the new audio overdrive functionality in gnome-shell 3.30. I think it would make sense to fix those in the same merge.

I've had well tested patches ready for all of this for quite awhile, but they required the [corrected shell theme versioning](https://github.com/NicoHood/arc-theme/pull/117), and I haven't had much time to work on this for the last weeks.

I can provide a new PR with all the fixes later this weekend.

> As far as I understood it: when I keep the the symlink and change the code in the 3.18 folder will this break the theme for gnome <=3.28?

This is correct, this is one of the reasons the earlier separation gtk and shell theme versioning was necessary. Removing the 3.30 symlink, and copying the whole 3.18 directory to 3.30 is probably OK for the moment.  However, at least the .gitignore should be updated to reflect that.

We could also symlink only the *-assets/ directories from 3.18, since they remain unchanged (for now), and only have a separate sass/ directory for newer versions.

> Did you use an old git revision where a gitignore was missing? There are lots of generated svg files.

No. The gnome-shell theme doesn't generate/render any assets, and AFAIK it never has. The svg files are "hard-coded" to the shell theme.

**Comment by spielkind** [comment]
> The updates to _common.scss looks mostly ok, but I think you missed updating the -slider-handle-radius.

It seems that they didn't changed this?
https://gitlab.gnome.org/GNOME/gnome-shell/blame/master/data/theme/gnome-shell-sass/_common.scss#L152

> However, there are also other updates to the slider scss, and also for the OSD audio-level bar, due to the new audio overdrive functionality in gnome-shell 3.30. I think it would make sense to fix those in the same merge.

I've also recognized this later, but actually I'm pretty new to this theme stuff :)


> I've had well tested patches ready for all of this for quite awhile, but they required the [corrected shell theme versioning](https://github.com/NicoHood/arc-theme/pull/117), and I haven't had much time to work on this for the last weeks.
> 
> I can provide a new PR with all the fixes later this weekend.

Sounds good! :+1:

**Comment by jnsh** [comment]
@spielkind, You're right about the `-slider-handle-radius` staying unchanged. My mistake for not checking this before commenting.

I added a replacement pull request with some additions in https://github.com/NicoHood/arc-theme/pull/129

**Pull request closed without merging**
