### PR TITLE
Optional resvg support

### PR DESCRIPTION
**Pull request by actionless**
https://github.com/RazrFalcon/resvg/

theme build time with inkscape:
real 96.79
user 287.94
sys 23.56

theme build time with resvg:
real 16.68
user 25.96
sys 7.61

### CODE REVIEW

**Comment by NicoHood** [comment]
Nice patch! Is resvg available for common distributions? For ArchLinux it is not, so inkscape as fallback is a must have. But that is not a problem with your patch, if I am not wrong.
https://aur.archlinux.org/packages/resvg/

Any special difference between this tool and inkscape?

**Comment by actionless** [comment]
it's a fresh library so it's not available in official repos yet, that's why it's support is optional

**Comment by actionless** [comment]
i've rebased on master to make the diff smaller

**Comment by actionless** [comment]
also if you wanna test it in arch linux please use `resvg-git` aur package instead, current stable version, 0.4, doesn't have the fix (linked to this PR) yet

**Comment by fossfreedom** [comment]
@NicoHood from a code-review point of view - looks good to go.

But I'm not an arch user so cannot test this without trying to figure out the compilation issues of the resvg github repo - can you please via that AUR?

**Comment by actionless** [comment]
Sorry, what?

**Comment by NicoHood** [comment]
I just dont use resvg. Assuming that fallback works without any problem, I will still compile the package using inkscape. Otherwise I'd have to to resvg into the official repos, which I dont want to do now.

I'd still merge the patch for those who want to use it for development.

**Comment by actionless** [comment]
if resvg is not installed it will work with inkscape

**Comment by actionless** [comment]
also while PR was open in upstream oomox theme keys changes, so i've updated theme keys and added small migration to the script

**Comment by fossfreedom** [comment]
Many thanks for this.

**Comment by actionless** [comment]
also thanks for reviewing this!

**Pull request merged**
