### PR TITLE
Cinnamon popupmenu

### PR DESCRIPTION
**Pull request by smurphos**
Hi,

This fixes an issue where the selection highlight on the Cinnamon popupmenu overlays the border image creating a bleeding effect. I've also added a visible popupmenu seperator. I think this does look better on larger more complex popup menus.

Before
screenshot-area-2019-02-11-093112

After
screenshot-area-2019-02-11-093155

### CODE REVIEW

**Comment by fossfreedom** [comment]
Looks good. cheers :)

**Comment by YorickPeterse** [comment]
Perhaps this is not the right place, but the newly added borders can look out of place quite easily. For example, the Volume control applet looks like this:

volume

The context menu for the grouped window list looks like this:

windows

Making the separators stand out more makes sense, but I think the current shade of blue is a bit too much.

**Comment by smurphos** [comment]
Thanks for the feedback.

Would a more subtle effect using the borders_color be more to your taste and more Arc?

screenshot-cinnamon-2019-02-19-073442

screenshot-cinnamon-2019-02-19-073740

**Comment by YorickPeterse** [comment]
@smurphos I think that looks more reasonable :smile:

**Comment by smurphos** [comment]
@fossfreedom @NicoHood 

Any preference?

**Comment by fossfreedom** [comment]
The last bunch of screenshots look good ... would go that route

**Pull request merged**
