### PR TITLE
Resolve jumping cinnamon panel icons - upstream #852

### PR DESCRIPTION
**Pull request by fossfreedom**
resolves upstream https://i.imgur.com/xps3bIc.mp4

tested cinnamon 3.4.6 on ubuntu 17.10

### CODE REVIEW

**Comment by NicoHood** [comment]
Have you generated the css files using gulp? I am unable to test right now. The changes look good to me though.

**Comment by fossfreedom** [comment]
Yep - I just take the PR scss, merge it - i.e. I dont merge the CSS stuff. Then generate the theme via gulp.  Install and test.

**Comment by NicoHood** [comment]
Nice! You should be familiar with gpg and commit signing, could you please enable commit signing for git and future commits? `git config --global commit.gpgsign true` and `git config --global user.signingkey <fingerprint>`

Lets merge this one.

**Comment by pizzadude** [comment]
@fossfreedom @NicoHood still happens on linux mint 18.3 cinnamon (ubuntu 16.04)

**Comment by NicoHood** [comment]
@pizzadude Can you please give us more detailed information on that? Which version/commit worked and which broke?

**Comment by pizzadude** [comment]
@NicoHood I'm not 100% certain but I'm pretty sure it happened after the latest update, that I just applied. I'm using @fossfreedom 's PPA.

If I run "aptitude show arc-theme" it shows the version is:

20180114-0+201801242050~ubuntu16.04.1

In /var/log/apt/history.log, it shows it was upgraded from:

20180114-0+201801182048~ubuntu16.04.1

Cinnamon version is: 3.6.7

This is what the issue looks like:

https://i.imgur.com/4HKUaE2.mp4

**Comment by fossfreedom** [comment]
@pizzadude at a guess maybe a cinnamon update broke the padding that fixed it last time?

Please have a look - give us a PR and we'll merge it in.

https://github.com/NicoHood/arc-theme/commit/a1a9822059d82e55aa1ca51f0834984fb2bdd03d

**Comment by pizzadude** [comment]
@fossfreedom I'm not a developer by any means.....but I fixed it. PR incoming...

**Comment by pizzadude** [comment]
Nevermind about the PR, as I have no idea how to work with these theme files except editing them directly. But I will show you how I fixed it:

On the ".panel bottom" line, if you add "margin-top: 0;" it fixes it
And vise versa for the ".panel top" line, adding "margin-bottom: 0;" it fixes it for the top panel.

The code looks like this, and in the current version, it starts on line 1306. In that revision you linked, it was on line 1308.

`  .panel-bottom .panel-launcher, .panel-bottom
  .launcher {
    margin-top: 0;
    margin-bottom: 0; }
  .panel-top .panel-launcher, .panel-top
  .launcher {
    margin-top: 0;
    margin-bottom: 0;
    padding-top: 0; }
`

@NicoHood @fossfreedom

**Comment by fossfreedom** [comment]
@NicoHood the file to change to include the changes is  common/cinnamon/sass/_common.scss

I can make the change and visually check the resultant CSS to ensure it look likes the above - do you want me to make the change directly?

**Comment by pizzadude** [comment]
well...i ended up submitting a PR but can you guys test it first : P

**Comment by NicoHood** [comment]
This is the PR:
https://github.com/NicoHood/arc-theme/pull/51

@fossfreedom Questions answered/solved?

**Comment by fossfreedom** [comment]
yep

**Pull request merged**
