### PR TITLE
Separate gtk3 and gnome-shell versioning

### PR DESCRIPTION
**Pull request by jnsh**
Since GTK3's version isn't tied to gnome desktop version any more, the versioning for shell and gtk3 themes should be separate as well.

Gnome-shell 3.30 requires some changes to the shell theme that don't work with older shell versions, so it would be great to have this merged before I submit the 3.30 updates.

There are some other minor shell theme issues introduced after gnome 3.22 as well, and fixing those properly requires correctly versioned shell themes.

### CODE REVIEW

**Comment by fossfreedom** [comment]
LGTM ... I will do some build tests today across different combinations to confirm the gtk and shell versions are correctly recognised.

**Comment by fossfreedom** [comment]
ubuntu budgie - new development bionic running - oracle vm virtualbox_106

This will not build on debian buster or ubuntu 18.04 since the mutter version is libmutter-2.  On 16.04 mutter is "libmutter"

The other issue is that we are now introducing a build dependency on mutter - which for other DE's such as XFCE not necessary.

**Comment by jnsh** [comment]
Thank you @fossfreedom from testing and feedback.

>This will not build on debian buster or ubuntu 18.04 since the mutter version is libmutter-2. On 16.04 mutter is "libmutter"

Sorry, I really should've thought about that. I'm quite sure this can be fixed simply, by additionally checking for older libmutter- API versions.

>The other issue is that we are now introducing a build dependency on mutter - which for other DE's such as XFCE not necessary.

That's only the case if you're actually building the gnome-shell theme, i.e. mutter isn't required if you pass the `--disable-gnome-shell` option to `autogen.sh`.

If you want to avoid extra optional build dependencies, I suppose we could just build for the newest available shell version by default if the `--with-gnome-shell=<version>` option is not being used, and either use the libmutter version only if it's available from pkg-config, or ditch the libmutter version detection altogether.

Let me know what you think, and I'll work out an updated pull request.

**Comment by fossfreedom** [comment]
From a packaging point of view the autodetection of the mutter version is very useful so I would kindly suggest extending your good work with libmutter, libmutter-1 and libmutter-2.

Forgot about the `--disable-gnome-shell` - that's fine, we'll stick with that.

As you say - if `--with-gnome-shell=version` is being used then there is no need to check for the mutter version.  This would be useful so that self-installers can install without needing a stack of development packages.

We'll clarify all of this via the README.

**Comment by jnsh** [comment]
Updated.

I decided to ditch the version checking with pkg-config and libmutter: In addition to the increased complexity of having to support multiple libmutter versions, the build script would break and have to be updated every time the libmutter API version is incremented.

Instead, the gnome-shell macro now parses the version from `gnome-shell --version` output. This may not be as robust as using pkg-config, but works better in this situation. I've tested the new macro quite thoroughly and it should be fail safe, and work with any shell version.

This means `gnome-shell` is now build dependency, if either `--disable-gnome-shell` or `--with-gnome-shell=<version>` is not used. Additionally `pkg-config` is no longer required to build the gnome-shell theme.

I think that `pkg-config` and `gtk-3.0` are now only used for auto-detecting gtk3 version during build, and not required if `--disable-gtk3` or `--with-gtk3=<version>` build options are used.

**Comment by fossfreedom** [comment]
excellent - works nicely across versions.  Tested the disable-gnome-shell and with-gnome-shell options as well as the autodetection.

+1

**Pull request merged**
