### PR TITLE
Added plank theme to makefile

### PR DESCRIPTION
**Pull request by NicoHood**
See #30 
Please review, then I will merge it manually do have the top commit GPG signed.

### CODE REVIEW

**Comment by NicoHood** [comment]
"Other options to pass to autogen.sh are" section in readme requires an update.

**Comment by fossfreedom** [comment]
Query - double checking ... this looks like that it only installs the plank theme for the Arc and "Arc-solid" folders - not for Arc-Darker and Arc-Dark and the solid variants?

**Comment by NicoHood** [comment]
Will plank look inside the folder `usr/share/themes/Arc/plank/`? I thought it would only work in the plank directory.

**Comment by fossfreedom** [comment]
indeed - it works in debian and ubuntu and I'm assuming its exactly the same as other distros

**Comment by NicoHood** [comment]
The file is now inside `/usr/share/themes/Arc/plank/dock.theme` which does not work for me. I have no idea why it should work for debian, dont see the reason or difference!?

**Comment by fossfreedom** [comment]
I ran this to confirm the package - indeed works fine.  very odd.

I'll try the alternate location as well.

```
dad@dad:~/Downloads$ dpkg -c arc-theme_20170302-2_all.deb | grep -i plank
drwxr-xr-x root/root         0 2017-06-08 16:53 ./usr/share/themes/Arc/plank/
-rw-r--r-- root/root      2479 2017-03-02 18:02 ./usr/share/themes/Arc/plank/dock.theme
drwxr-xr-x root/root         0 2017-06-08 16:53 ./usr/share/themes/Arc-Dark/plank/
-rw-r--r-- root/root      2479 2017-03-02 18:02 ./usr/share/themes/Arc-Dark/plank/dock.theme
drwxr-xr-x root/root         0 2017-06-08 16:53 ./usr/share/themes/Arc-Darker/plank/
-rw-r--r-- root/root      2479 2017-03-02 18:02 ./usr/share/themes/Arc-Darker/plank/dock.theme
```

**Comment by fossfreedom** [comment]
@NicoHood ok - just to double check your testing - in plank preferences you have set the theme to be "GTK+" which means it picks up the style from /usr/share/themes/Arc/plank/dock.theme ?

Yeah - adding to /usr/share/plank/themes/Arc/dock.theme makes "Arc" appear in the list of plank preferences themes

**Comment by NicoHood** [comment]
"in plank preferences you have set the theme to be "GTK+" which means it picks up the style from /usr/share/themes/Arc/plank/dock.theme"

No, I did not know about this. That was the trick. I was searching for "Arc". We need to add this to the readme then as well. Will push my latest commit, please review again.

**Comment by fossfreedom** [comment]
expertly done @NicoHood  !

**Comment by NicoHood** [comment]
@fossfreedom so please checkout the new release. If anything critical is still wrong we can tag another release within the next days, so everything will be okay in your final package.

**Comment by fossfreedom** [comment]
@NicoHood ta

Where can I find your public key file?  I need to get your gpg fingerprint to verify the signed tarball

**Comment by NicoHood** [comment]
from the keyservers or from contact.nicohood.de

**Comment by fossfreedom** [comment]
@NicoHood tarball and signed key works nicely.  Thanks.

Onwards to the next version!

**Pull request merged**
