### PR TITLE
Fix mismatched "}" for GNOME 3.18 NEW

### PR DESCRIPTION
**Pull request by FrancescoCuiusIuculano**
Rebased #111

### CODE REVIEW

**Comment by NicoHood** [comment]
Please remove the first commit, it is the wrong place for it.

**Comment by FrancescoCuiusIuculano** [comment]
Sorry, I noticed it only after the PR was submitted, now it's ok

**Comment by NicoHood** [comment]
The indention looks a bit wrong. Can we fix this or would it require tons of rework?

**Comment by FrancescoCuiusIuculano** [comment]
What do you mean exactly?

**Comment by FrancescoCuiusIuculano** [comment]
Ah, I see. Well, I tried to adjust all the things, but the code already has some misalignments and I ended up messing things up even further. Maybe someone more expert than me can do a better job, but I don't think it's worth the effort, since there are quite a lot of lines

**Pull request merged**
