### PR TITLE
Cinnamon Update

### PR DESCRIPTION
**Pull request by smurphos**
Cinnamon 4 support
Add missing features from Cinnamon 3.8
Add missing features for Cinnamon 3.6
Once over and bugfix

I'm hoping to have this done in the next day or so before i go away for the Xmas week....

### CODE REVIEW

**Comment by smurphos** [comment]
All done. I think I've captured all the changes in the two short screengrab vids in the attached zip. Merry Xmas to you all...

[Screengrabs.zip](https://github.com/NicoHood/arc-theme/files/2708359/Screengrabs.zip)

**Comment by JirkaVebr** [comment]
@smurphos Excellent work! Thak you so much for this! :slightly_smiling_face:

**Comment by fossfreedom** [comment]
Hi ... many thanks for all of this.

Please can I ask you to rereview each of the commits.

The indentation looks wrong. Spaces not tabs and for example 

{ should be after a statement not below, 

stuff within {} should be indented by a couple of spaces so that you can read which bit of scss is denoted in which block.

**Comment by smurphos** [comment]
Thanks @fossfreedom. I think I followed the existing code styling in most cases in the scss. The svgs are a direct copy of existing assets with a colour tweak.

There may be some areas with 4 spaces instead of 2 in the scss. I can review in the New Year, I'm away from home for a week now.

**Comment by smurphos** [comment]
No worries. There are a few bits were I strayed from the existing code-style which I will fix in another PR in the new year. I'll also take another look at the colour used for progress and the new hover highlighting 

Do you have any objections to me hosting a build on Cinnamon Spices https://cinnamon-spices.linuxmint.com/themes with appropriate accreditation?

**Pull request merged**
