### PR TITLE
Make better use of autotools

### PR DESCRIPTION
**Pull request by chewi**
This is a work in progress so please don't merge it yet. There are a lot of changes so I wanted to run it by you before I do too much more work on it. Nearing the end, mainly compile-gresources.sh still to deal with, though I'm only changing GTK+2, GTK+3, and XFWM4 for now.

### CODE REVIEW

**Comment by jnsh** [comment]
I can definitely have a better look and give feedback either way, but the cleaner you can make it, the better.

In any case, could you give a little more detailed description of what this PR does. I've read some of your goals from #26, but I'm a bit uncertain what's been implemented here. Looks like you've at least moved the asset rendering from the render-assets scripts to Makefiles (which is very nice), but some of the changes seem unrelated to that?

I'm don't know about `make dist`. Better check that from @NicoHood

**Comment by NicoHood** [comment]
What is make dist?

**Comment by jnsh** [comment]
@NicoHood I've never had to use it so I'm not 100% sure, but IIUC `make dist` is meant to be used for making tarballs for a release.
See https://www.gnu.org/prep/standards/html_node/Standard-Targets.html

**Comment by chewi** [comment]
That's right. I thought you were using it because you already have `EXTRA_DIST` in one or two places. Even if you don't use it, I don't like the idea of breaking it so I've made the changes and got it working. More later.

**Comment by chewi** [comment]
Hmm, not so good at the moment. The Dark theme is not looking very dark under GTK+3! It works under GTK+2 though. I thought perhaps the ../assets paths in the XML were breaking it but I changed this by using a symlink and it made no difference. I'll keep digging.

**Comment by fossfreedom** [comment]
I've run through quite a few compilation options and this PR works quite nicely.

Excellent work @chewi 

The --with-gtk3 option is broken for version 3.28/3.30 - but this is an existing issue - nothing to do with this PR.

Thanks

**Comment by fossfreedom** [comment]
From a major distribution  point of view fedora has maintainer issues so they are not yet using this repo.

Agree and disagree. I did take into account the distro situation.

Debian will not freeze until end of Jan ... so further testing feedback is useful.

Ubuntu will not freeze until March.

There are no other major fixed release major distros.   Arch and Manjaro are rolling releases and Nico can manage fixes.

Will go for a release now. 

Nico I would like to plan for an end of year begin Jan release to meet debian Ubuntu and maybe fedora freeze dates.

**Comment by jnsh** [comment]
Did you account the fact that this breaks oomox support as I mentioned? If it's OK to break, why do we even support it in the first place?

Furthermore, this PR doesn't provide any real improvements to the build system, but is basically just cleanups and infrastructure improvements. I don't think that justifies rolling out a release that breaks something else within the theme.

Either the oomox support should be fixed before the release, or this PR could be postponed to properly polish and fix any issues with it for the future releases.

**Comment by fossfreedom** [comment]
Release now. Can resolve subsequently. If we don't release now then this PR will not be available to Debian until July next year and Ubuntu until May.

I will not allow major changes close to freeze dates.

**Comment by NicoHood** [comment]
All issues for the next release are closed. If nobody complains I will push out a new release tomorrow. If there is still something wrong with it, I have no problem is pushing another release within the next weeks for quick fixes.

**Comment by fossfreedom** [comment]
Thanks Nico. Good job from everyone who contributed. This is a big release. IMHO more than a minor point release. But I will leave that to you.

**Comment by NicoHood** [comment]
We do not have major or minor releases, as the date is used as version number. But its quite major, yes.

**Comment by fossfreedom** [comment]
Sure. I was referring to the release description.  Sorry for the confusion

**Pull request merged**
