### PR TITLE
Metacity - add buttons to modal geometry & fix attached dialog titlebar.

### PR DESCRIPTION
**Pull request by smurphos**
Closes - #152

### CODE REVIEW

**Comment by NicoHood** [comment]
If that fixes the issue and has no other regressions, we should merge it. I personally dont know what side effects this has.

**Comment by smurphos** [comment]
It's basically just giving the modal dialogs a normal size title-bar and a close button. Whether lack of them is a bug or not is debatable as any modal window should have a close, ok or cancel button in any case to dismiss the window and the original set-up to not have them was likely a design decision  - but it seems to bother users. By the way this isn't Cinnamon specific - same thing happens in Mate.

Pics from Chrome save as dialog

Before 

screenshot-screen-2018-12-09-101834

After

screenshot-screen-2018-12-09-101919

**Comment by smurphos** [comment]
Actually Nico - you might want to scrap this unless you want the close button - the OP is that issue just needs to change a setting in his Window Manager.

**Comment by smurphos** [comment]
I've marked this WIP as I think the lack of a title in attached modal dialogs is probably a bug. It's not pretty in any case.

**Comment by NicoHood** [comment]
Which title?

About the close button: How do other themes behave in this case?

**Comment by smurphos** [comment]
So we've got three types of dialog windows all of which have separate theming in metacity.

Normal Dialog - users can flip between focussing on it and the parent window. Both windows can be moved around independently. You can close the parent and leave the dialog open.

Modal Dialog - can't focus on or close the parent until dismissed. Both windows can be removed around independently.
or
Attached Modal Dialog - can't focus on the parent until dismissed and cannot be moved independently of the parent window. 

The latter only occurs if the user switches on a Window Manager setting in current Cinnamon. The default is the regular modal dialog. 

What other themes do -

Adwaita - Titlebar with title on all three, no buttons on any of them.
Numix - Titlebar with title on all three, button on dialogs but not modal dialogs or attached modal dialogs.
Adapta - Same as Numix
Materia - Titlebar with title on all three, no buttons on dialogs, but does have buttons on modal dialogs. No buttons on attached modal dialogs.
Mint X + Y - Titlebar with title and buttons on dialogs and modal dialogs, empty solid titlebar on attached modal dialogs.
Current Arc - Titlebar with title dialogs and modal dialogs, empty solid titlebar on attached modal dialogs. No buttons on any

So two questions arise  - do you want the attached dialog fixed so it has a title in the titlebar - it is ugly if users enable it as evidenced by the linked issue. The alternative is to have no titlebar and just a plain bordered window.

And do you want a close button on dialogs and/or modal dialogs and/or attached modal dialogs assuming it is possible in the latter case.

Sorry for any confusion caused - TBH today is the first time I switched on the attached dialog mode in Cinnamon and realised that was what was causing the issue raised and it wasn't just a lack of buttons that was the problem.

**Comment by smurphos** [comment]
Arc with the PR - Titlebar with title dialogs, modal dialogs & attached modal dialogs. Buttons on dialogs & modal dialogs

**Comment by smurphos** [comment]
@fossfreedom 

It fixes the lack of titlebars in attached modal dialogs which was actually the problem in the original issue.  These only apply when a user has switched on an off by default setting in Cinnamon's Window Manager. Not sure if any other DE uses the metacity-theme-3 that this would also impact on.

As it stands it also adds titlebar buttons to regular unattached modal dialogs. This is really a design decision to be made, as modal dialogs should always have a close / dismiss / cancel button. 

I can revise the PR to limit it to fixing the issue if you like.

**Pull request merged**
